### ISSUE TITLE
Can't get this script to run.

### ISSUE THREAD

**Issue by JamesO2x** [Gewerd-Strauss/GeneralHealthBots.ahk#4]
I tried getting this script to run, but it keeps running into errors involving libraries that don't exist.

Just running the `GeneralHealthBot.ahk` script breaks at line 159 with this error:

> Error at line 159.
> 
> #include file
> "C:\users\USERNAME\Documents\AutoHotKey\Lib\IniFileCreator_v8.ahk"
> cannot be opened.
>
> The program will exit.

I did a search on my computer and the "AutoHotKey\Lib" folder doesn't even exist in my documents folder.

So I tried a search for `IniFileCreator_v8.ahk` and no such file exists on my computer. It doesn't seem like this "library" is a standard feature of my default AutoHotKey installation.

Next I did a search online for "IniFileCreator_v8.ahk" to see if I could find the missing file. It wasn't straightforward to find it, but I did come across this "archive" post on the AHK forums:

> https://www.autohotkey.com/boards/viewtopic.php?style=17&f=6&t=3216&start=60

It contains a link to a massive 7zip backup of (apparently hard to find) library scripts. I had to dig into the zips to find the necessary script at buried (in a ZIP within a ZIP) here:

`rbrtryn_3-04-2014.7z\robertcollier4_pack\AutohotkeyDotNet_Megapack.7z\~toralf\IniSettingsEditor\IniFileCreator_v8.ahk`

I tried moving that to the User Documents folder that it expects it at. Then I got another error because the IniFileCreator_v8.ahk was looking to include: `Func_IniSettingsEditor_v6.ahk` on line 79.

So I copied THAT file into the Lib folder that I had created, and it still couldn't find it. I'm guessing because the original `GeneralHealthBot.ahk` is considered the root directory, and so `IniFileCreator_v8,ahk` is maybe looking there?

Next I tried to copy both files to the `GeneralHealthBot.ahk` directory and created a new "lib' folder there to put them in. Then I modified the "include" paths to point to those new files.

So I modified the include paths in both files, and then I get an error because of a missing `/Anchor/Anchor_v3.3.ahk` file...

I want to try this health script out, but I'm not gonna spend an unknown number of hours debugging it to hunt down all the obscure linked libraries that it is trying to reference.

Please consider including copies of all the necessary libraries in a "lib" folder for this script, and point the INCLUDE commands to the proper relative locations, that way the source of this script is "complete" and can be run "out-of-the-box". 

Having to download a 24mb 7zip archive (containing roughly 2707 files, nested in sub-folders) on a forum post from 2018, just to find a handful of AHK files, isn't a fun experience.

**Comment by Gewerd-Strauss** [comment]
Welp. 

That is one hell of a sluggish mistake I did there. That file is not bundled because it _shouldn't_ be. However, I obviously failed clean-ups. I am sorry. The problem _should_ be fixed now. #5


---

>Please consider including copies of all the necessary libraries in a "lib" folder for this script, and point the INCLUDE commands to the proper relative locations, that way the source of this script is "complete" and can be run "out-of-the-box".
Having to download a 24mb 7zip archive (containing roughly 2707 files, nested in sub-folders) on a forum post from 2018, just to find a handful of AHK files, isn't a fun experience.

I know the pain, because I went through the same pain hunting down that file for my own usage. I had to dig it up as well.


---
>I did a search on my computer and the "AutoHotKey\Lib" folder doesn't even exist in my documents folder.

Check out the documentation for v1 on the [Library](https://www.autohotkey.com/docs/Functions.htm#lib), and anecotally the documentation on the [#Include](https://www.autohotkey.com/docs/commands/_Include.htm)-directive. 
While this has nothing to do with the issue at hand, I am confused as to why you don't have that folder. 


From the documentation on Function-Libraries:
![image](https://user-images.githubusercontent.com/80548781/145718652-c116ea55-1d1f-4346-9c21-4a0c4f135e4e.png)

**Comment by Gewerd-Strauss** [comment]
Edit:

If you want to, you could try again, and you shouldn't have any issues now. Please report back if that is not the case, because then I am _very_ confused. 

This was pretty much my first ever published project, and old as fuck. I might revamp it at some point in the future, but currently it is feature-complete - unless I start pushing accidental test stages again, like I obviously did here.

**Comment by JamesO2x** [comment]
I just checked all 3 of those locations, and none of them have a "lib" folder. Even the "standard library" in the autohotkey install directory is missing. The only folder there is the "Compiler" one. I'm 99% sure that I did a standard installation of AHK, so if these directories were supposed to be created (and populated with library scripts), I have no idea what went wrong.

I'm gonna try a full uninstall/reinstall of AHK, and see what happens. I'll retry your script and report back here if I have any issue. It might be a while before I get around to it though, as I've got some other stuff going on.

**Comment by Gewerd-Strauss** [comment]
I just checked my standard library location, and I don't have  a `lib`-folder at `directory-of-the-currently-running-AutoHotkey.exe\Lib\` either. Which is weird, but I also don't use 

If that doesn't help, you might wanna try an actual reinstall, and then proceed to the [forum boards](https://www.autohotkey.com/boards/) and [subreddit](https://reddit.com/Autohotkey) to try and figure out what the hell is going on.
Good luck. That sounds very weird. 

---

Alternatively, I realised I have not supplied a compiled version, but I suppose I could do so.
In that case, no ahk instance should be needed, and these problems shouldn't persist because the compiler will compile all necessary files as well. 
I usually prefer sharing and distributing plain text instead of compiled files for safety, trust and ease of access reasons.

**Comment by JamesO2x** [comment]
I just did a clean re-install, just to confirm, AHK definitely does not create any LIB folders in the documents directory or its install directory.

I tried looking up info on the "standard library" and found a lot of conflicting information. It appears that the "standard library" doesn't actually come standard with an AHK install. It's just something that various forum members sort of conglomerated together, and there may (or may not) be multiple conflicting "standard" library versions that are floating around the internet in various ZIP files.

What I was able to find were a bunch of archived forum posts, some with download links -- but all the links were broken and many posts were over 10 years old.

- [Ahk Standard Library Collection, 2014 May (+Gui) ~ Libs: 100 - AutoHotkey Community](https://www.autohotkey.com/boards/viewtopic.php?f=6&t=3643)
- [Standard Library Functions - Scripts and Functions - AutoHotkey Community](https://www.autohotkey.com/board/topic/20463-standard-library-functions/)
- [[Basic]AutoHotkey Help with Standard Library - Scripts and Functions - AutoHotkey Community](https://www.autohotkey.com/board/topic/67248-basicautohotkey-help-with-standard-library/)
- [Broken AutoHotkey.net Links Updated 5-22-2013 - Ask for Help - AutoHotkey Community](https://www.autohotkey.com/board/topic/83238-broken-autohotkeynet-links-updated-5-22-2013/)

One post seems to hint that the "newer versions of AHK have COM built-in so you don't need the COM library".

I didn't know AHK was such a mess. Apparently there's also a difference in compatibility between AHK 32bit and AHK 64bit, and possibly an alternative branch of AHK called AHK_L ? I usually just pick the basic express installation.

I've generally not had much issue creating my own AHK scripts, or running ones I find online. But This GeneralHealthBot script is also one of the more complex scripts I've seen.

---

Anyway, I downloaded your `GeneralHealthBot` script again and tried to run it. I now get this error instead:
![Imgur](https://i.imgur.com/mkkreT3.png)

This is on a clean install of AHK 1.1.33.10 (latest stable version), using the "express install" default settings.

It looks like the issue specifically is a function call `ttip` which I can't find any documentation for. My guess is that its some sort of custom ToolTip function? I opened the `GeneralHealthBots` folder as a project in VS Code, so I could search every file for any references to `ttip` and apparently this single instance in this single file `C:\GeneralHealthBots.ahk-main\GeneralHealthBots\includes\f_Confirm_Question.ahk` is the only time `ttip` is ever mentioned.

So I'm guessing that the script fails because its calling a `ttip` function that isn't defined anywhere.

I did a google search for "AHK ttip" to see if this might be one of the "standard functions" that isn't included with AHK, and the only reference to TTIP that I could find was in this FTP script: [ahk-libs/Example_Async.ahk at master · rshipp/ahk-libs](https://github.com/rshipp/ahk-libs/blob/master/FTPv2/Example_Async.ahk)

But even here, they define what the function does lower in the script:

```ahk
TTip(Message="") {
	ToolTip %Message%
}
```

No where in the `GeneralHealthBots` scripts folder does `TTIP` seem to be defined this way (to actually call a tooltip). I'm guessing maybe you had it defined in some INCLUDE file that was maybe not added to the github?

> EDIT: This forum post references the same error in a similar way: https://www.autohotkey.com/board/topic/88975-ftp-help/

If I comment-out this line and try running the script to see what happens, I now get this error:
![Imgur](https://i.imgur.com/EW7BuNI.png)

It seems like something with the way you are using Include files and functions is not quite right -- or possibly, you're calling files/functions which doesn't exist on an average user's clean install of AHK and only works on your machine.

Maybe its possible that you've downloaded some of these old "standard libraries" years ago and forgot about it, and have been using them without really realizing it? Or, are you possibly using AHK 2.0 or AHK_L versions? Because I think the syntax is different from the stable 1.0 release, and thus scripts won't be compatible.

I'm not really sure. I'm an amateur coder with limited knowledge on this complex stuff, so that's the perspective I'm coming from. This is just my experience trying to run this script on a clean install of AHK.

**Comment by Gewerd-Strauss** [comment]
Alright. 

Fuck this shit. 
I'll do a deep look over on my end and come back at you in two days. 

`Updater.ahk` should contain an instance of my ttip, function, but apparently it did not. In the meantime, I did hunt down why this is so messy - besides me being slightly dumb some of the time.


> ttip()

... is just a multipurpose wrapper to the tooltip for me as well. My version has a few modes for quick configuration of rudimentary tooltips, but mostly it's just out of laziness - I don't want to set up a timer everytime I call a tooltip temporarily. So this is just a wrapper around some positioning, timer and permanent tooltip calls. I never looked on the web, but I am obviously not the only one, but I know of HotKeyIt's [TT.ahk](https://github.com/HotKeyIt/TT/blob/master/TT.ahk), which is much more expansive and utter overkill for my needs. 



# As a warning 

- Updater.ahk is _still_ semi-finished only. I don't even think I will finish it the way it was originally planned, instead of just reworking it to be much simpler. I mean, it works 98% of the way. Just don't use it on this script. This program is finished anyways, so I am unlikely to commit any updates beyond bugfixes to unnecessary simple mistakes like the ones you are reporting here. 

This is kinda embarassing - while I am by no means a professional, this is still a passion for me :P And quite apparently, this program is more bug-laden than I am even remotely comfortable with. 

---
> I didn't know AHK was such a mess. Apparently there's also a difference in compatibility between AHK 32bit and AHK 64bit, and possibly an alternative branch of AHK called AHK_L ? I usually just pick the basic express installation.

![image](https://user-images.githubusercontent.com/80548781/145729284-ed9dad63-5404-4a7a-8d70-dc80b768cb9d.png)


I get confused as well.

Ahk is... _interesting_, to say the least. From my understanding, which is not perfect, there's nowadays basically only 

* **ahk_L** (v.1.1., forked by Lexikos from the _original release v.1.0. 
  It became more popular than v.1.0, the author of v.1.0 stopped development and so the community decided to re-designate v.1.1/AHK_L as the main release. ) 
 This is the version you will find the most scripts and libraries for online. It has been around the longest, is stable and widely used. However, it has its flaws, the most obvious is the awkward mix of legacy Commands (e.g. `ImageSearch, OutputVarX, OutputVarY, X1, Y1, X2, Y2, ImageFile`, where `OutputVarX/Y` are return values, and all others are "parameters") and actual functions, which actually return a value with a `return value`-statement within the function body, and are called with syntax `OutPutVar:=Function(InputVar)`
* **ahk_v2** is in its first beta as of July this year. It aims to unify the syntax by getting rid of those pesky Commands, and only using functions. There are also no longer legacy-assignmends (`Variable=1` will not be valid anymore, but must be `Variable:=1`). There are obviously a lot of other changes, but I am not familiar with v2. v1 and v2-scripts are not intercompatible without refactoring to accomodate for the heavy syntax differences.

I hope that one day, once v2 is fully out of beta, we can get to the point where the major public libraries will be ported over by the community, and then the community can finally move on to v2 and recommend it to new users - which you really can't right now. In v2, because it is still up for grabs and in beta, if you don't _know_ what's going on you're gonna have a much worse time compared to v1 - or so I've heard. Would still be nice to finally move on, but who knows how long that's gonna take.

--- 

I mean, I did fix both issues you've pointed out.
Problem fixes: Pull Request #6

**Comment by JamesO2x** [comment]
Hey, I just wanted to let you know that I copied the line changes you made, and now the script is running as intended on my machine. This is a really neat script, and I can see the potential in it for making other general purpose notifications.

Thanks for all help! And thanks for explaining what these functions are supposed to do and your thought process behind it all.

No need to feel embarrassed, I tend to just add stuff onto my scripts too, and it can pile up over time, sometimes forgetting what parts are "necessary" and which parts were "experimental" lines of code.

Now that I can get this script running, and have spent a bit looking at the files, I'm starting to get an understanding for how it works.

---

I really love AHK because its simple to use, but high-level stuff can get quite complex! It would be nice to see some sort of centralized AHK package database, kinda like PIP in python.

**Comment by Gewerd-Strauss** [comment]
> This is a really neat script, and I can see the potential in it for making other general purpose notifications.

Yeah, for some time I thought about just baking in a third one to let users set meaning of themselves. I guess I could modify it so that one could set their own messages (title is already customisable), but that is rather low on my priority list. I am currently swamped with work for university, winter depression is kicking in and I get little to to spend on hobbies - and I've got other scripts to drive development on for personally more pressing matters. All I publish tends to be stuff I need myself firsthand, but then tend to think "fuck it, maybe someone else might find it useful as well, might as well put it out there". 

However, for that to be more expansive (i,e, set any number of notifications) I'd need to make the logic recursive - which means rewriting 95% of the entire code flow - from GUI creation over timers over god knows what. I am not in need to something like that - if I would add a single one and allow rework of the reminder text, one would in theory have three blank slates to use as they see fit. That's something to think about, but again - low priority at the time.

---

> No need to feel embarrassed, I tend to just add stuff onto my scripts too, and it can pile up over time, sometimes forgetting what parts are "necessary" and which parts were "experimental" lines of code.

Well, yes. But usually I don't publish code that's _this_ bad. Sure, I get the odd bug I didn't anticipate the second someone else runs it, but not to this degree - all these mistakes happened due to sloppy control on my end, this entire issue shouldn't ever exist :P

---

>I really love AHK because its simple to use, but high-level stuff can get quite complex! It would be nice to see some sort of centralized AHK package database, kinda like PIP in python.

There kinda is, it is called "ahkscript". Formerly hosted on ahkscript.org, which is now defunct. Nowadays, "ahkscript" is maintained on [GitHub](https://ahkscript.github.io/). To my knowledge, there is no full database backup of the OG ahkscript.org - which btw is the page where the scripts of the hard-to-find-zip you've mentioned were originally hosted on. That page went down at some point, and the community started contributing whatever pieces of the database they could salvage from personal duplicates, creating that zip. 
Aside from that, the actual Number 1 place to start is the forum I mentioned - it has a shitton of posts sharing libraries and code. 

But yeah, there is no centralised place like PIP or CRAN for R. The language is comparatively niche, I suspect it is simply not worth the hassle for any one party to set that up.

---

Always happy to help, especially if it is at my own fault :P

**Comment by JamesO2x** [comment]
Thanks for all the info. I didn't know about the ahkscript.org situation.

> All I publish tends to be stuff I need myself firsthand, but then tend to think "fuck it, maybe someone else might find it useful as well, might as well put it out there".

I feel you! I do the same. I've got a couple unpublished scripts that are perpetually "work in progress" because I just add stuff that only I would find useful to it. I might push them out one day, but not yet.

Anyway, thanks for the script, and for the help!
